import secrets

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.config import Settings, get_settings
from app.database import Base
from app.deps import get_db


def _valid_settings(**overrides):
    values = {
        "development_mode": False,
        "secret_key": secrets.token_hex(32),
        "session_encryption_key": secrets.token_hex(32),
    }
    values.update(overrides)
    return Settings(**values)


def test_development_mode_defaults_to_false():
    """Production deployments without explicit DEVELOPMENT_MODE must get secure cookie settings."""
    s = Settings(_env_file=None)
    assert s.development_mode is False, (
        "development_mode must default to False so cookies get the Secure flag in production "
        "unless explicitly set to True in a .env file"
    )


@pytest.mark.parametrize(
    ("secret_name", "placeholder"),
    [
        ("SECRET_KEY", "change-me-to-a-random-32-char-string"),
        ("SESSION_ENCRYPTION_KEY", "change-me-to-a-64-char-hex-string"),
        ("SECRET_KEY", ""),
        ("SESSION_ENCRYPTION_KEY", ""),
    ],
)
def test_template_secret_placeholders_fail_in_production(secret_name, placeholder):
    values = {
        "secret_key": secrets.token_hex(32),
        "session_encryption_key": secrets.token_hex(32),
    }
    values[secret_name.lower()] = placeholder

    with pytest.raises(ValueError, match=secret_name):
        _valid_settings(**values).warn_insecure_defaults()


@pytest.mark.parametrize(
    ("secret_name", "value", "message"),
    [
        ("secret_key", "a" * 31, "at least 32 bytes"),
        ("secret_key", "a" * 32, "low-entropy"),
        ("session_encryption_key", "a" * 63, "exactly 64 hexadecimal"),
        ("session_encryption_key", "z" * 64, "exactly 64 hexadecimal"),
        ("session_encryption_key", "a" * 62 + "  ", "exactly 64 hexadecimal"),
        ("session_encryption_key", "a" * 64, "low-entropy"),
    ],
)
def test_insufficient_or_malformed_production_secrets_fail(secret_name, value, message):
    with pytest.raises(ValueError, match=message):
        _valid_settings(**{secret_name: value}).warn_insecure_defaults()


def test_generated_production_secrets_start_successfully(monkeypatch):
    """The production lifespan accepts secrets generated by the documented command."""
    from app.main import create_app

    monkeypatch.delenv("DEVELOPMENT_MODE", raising=False)
    monkeypatch.setenv("SECRET_KEY", secrets.token_hex(32))
    monkeypatch.setenv("SESSION_ENCRYPTION_KEY", secrets.token_hex(32))
    get_settings.cache_clear()

    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)

    def override():
        db = Session()
        try:
            yield db
        finally:
            db.close()

    app = create_app()
    app.dependency_overrides[get_db] = override
    try:
        with TestClient(app) as client:
            assert client.get("/api/v1/health").status_code == 200
    finally:
        app.dependency_overrides.clear()
        Base.metadata.drop_all(bind=engine)
        engine.dispose()
        get_settings.cache_clear()


def test_short_session_encryption_key_raises():
    """_key_bytes must raise ValueError for keys shorter than 64 hex chars."""
    from app.services.oidc import _key_bytes

    with pytest.raises(ValueError, match="SESSION_ENCRYPTION_KEY"):
        _key_bytes("aabbcc")  # 6 chars — too short


def test_valid_session_encryption_key_accepted():
    from app.services.oidc import _key_bytes

    key = _key_bytes("a" * 64)
    assert len(key) == 32


def test_odd_length_session_key_raises():
    from app.services.oidc import _key_bytes

    with pytest.raises(ValueError):
        _key_bytes("a" * 63)  # 63 hex chars — odd length
